version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: admin-front-app
    env_file:
      - .env.docker
    ports:
      - "85:85"
    restart: unless-stopped
    networks:
      - portfolio-network

networks:
  portfolio-network:
    external: true
